# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Lense.create(
    name: "Canon Super",
    camera_type: "SLR",
    brandname: "Canon",
    mount_type: "Canon EF-M",
    photos: URI("http://res.cloudinary.com/thewagon/image/upload/v1498026626/lens10_dvjuzd.jpg"),
    condition: "Good",
    description: "Great cam",
    price: Faker::Number.number(3),
    aperture_min: "4",
    aperture_max: "5.6",
    focal_length_min: "18",
    focal_length_max: "55",
    image_stabilization: "Yes", )
  Lense.create(
    name: "Canon Extra",
    camera_type: "Mirrorless",
    brandname: "Canon",
    mount_type: "Canon EF-M",
    photos: URI("http://res.cloudinary.com/thewagon/image/upload/v1498026626/lens9_on6eye.jpg"),
    condition: "Good",
    description: "Great cam",
    price: Faker::Number.number(3),
    aperture_min: "10",
    aperture_max: "20",
    focal_length_min: "18",
    focal_length_max: "55",
    image_stabilization: "No", )
  Lense.create(
    name: "Canon Hola",
    camera_type: "DSLR",
    brandname: "Canon",
    mount_type: "Canon EF-M",
    photos: URI("http://res.cloudinary.com/thewagon/image/upload/v1498026626/lens8_xz2r3y.jpg"),
    condition: "Poor",
    description: "Great cam",
    price: Faker::Number.number(3),
    aperture_min: "4",
    aperture_max: "5.6",
    focal_length_min: "18",
    focal_length_max: "55",
    image_stabilization: "Yes", )
  Lense.create(
    name: "Canon Div",
    camera_type: "DSLR",
    brandname: "Canon",
    mount_type: "Canon EF-M",
    photos: URI("http://res.cloudinary.com/thewagon/image/upload/v1498026626/lens10_dvjuzd.jpg"),
    condition: "Good",
    description: "Great cam",
    price: Faker::Number.number(3),
    aperture_min: "4",
    aperture_max: "5.6",
    focal_length_min: "18",
    focal_length_max: "55",
    image_stabilization: "No", )
  Lense.create(
    name: "Canon Waw",
    camera_type: "DSLR",
    brandname: "Canon",
    mount_type: "Canon EF-M",
    photos: URI("http://res.cloudinary.com/thewagon/image/upload/v1498026625/lens7_nigcu2.jpg"),
    condition: "Mint",
    description: "Great cam",
    price: Faker::Number.number(3),
    aperture_min: "4",
    aperture_max: "5.6",
    focal_length_min: "10",
    focal_length_max: "24",
    image_stabilization: "No", )
  Lense.create(
    name: "Nikon Super",
    camera_type: "SLR",
    brandname: "Nikon",
    mount_type: "Canon EF-M",
    photos: URI("http://res.cloudinary.com/thewagon/image/upload/v1498026626/lens10_dvjuzd.jpg"),
    condition: "Good",
    description: "Great cam",
    price: Faker::Number.number(3),
    aperture_min: "4",
    aperture_max: "5.6",
    focal_length_min: "18",
    focal_length_max: "55",
    image_stabilization: "No", )
  Lense.create(
    name: "Nikon Super",
    camera_type: "DSLR",
    brandname: "Nikon",
    mount_type: "Canon EF-M",
    photos: URI("http://res.cloudinary.com/thewagon/image/upload/v1498026626/lens10_dvjuzd.jpg"),
    condition: "Good",
    description: "Great cam",
    price: Faker::Number.number(3),
    aperture_min: "4",
    aperture_max: "5.6",
    focal_length_min: "250",
    focal_length_max: "300",
    image_stabilization: "Yes", )
  Lense.create(
    name: "Fuji Super",
    camera_type: "Mirrorless",
    brandname: "Fujifilm",
    mount_type: "Fujifilm X Mount",
    photos: URI("http://res.cloudinary.com/thewagon/image/upload/v1498026626/lens10_dvjuzd.jpg"),
    condition: "Good",
    description: "Great cam",
    price: Faker::Number.number(3),
    aperture_min: "4.2",
    aperture_max: "5.8",
    focal_length_min: "24",
    focal_length_max: "25",
    image_stabilization: "Yes", )
  Lense.create(
    name: "Fuji Super",
    camera_type: "DSLR",
    brandname: "Fujifilm",
    mount_type: "Fujifilm X Mount",
    photos: URI("http://res.cloudinary.com/thewagon/image/upload/v1498026626/lens10_dvjuzd.jpg"),
    condition: "Good",
    description: "Great cam",
    price: Faker::Number.number(3),
    aperture_min: "4",
    aperture_max: "5.6",
    focal_length_min: "18",
    focal_length_max: "55",
    image_stabilization: "No", )
  Lense.create(
    name: "Fuji Super",
    camera_type: "Mirrorless",
    brandname: "Fujifilm",
    mount_type: "Fujifilm X Mount",
    photos: URI("http://res.cloudinary.com/thewagon/image/upload/v1498026626/lens10_dvjuzd.jpg"),
    condition: "Poor",
    description: "Great cam",
    price: Faker::Number.number(3),
    aperture_min: "4",
    aperture_max: "5.6",
    focal_length_min: "100",
    focal_length_max: "300",
    image_stabilization: "Yes", )
